Repository wecode-bootcamp-korea/18-1st-LINEAVENGERS-frontend, pull requests merged in 2021-03, with the labels that each got.

#20 [18기 박경현] 리뷰 수정사항 반영 / 로그인, 로그아웃 기능 추가
  .gitignore
  package-lock.json
  package.json
  public/Data/CategoryData.json
  public/Data/CommonData.json
  public/Data/MainBannerData.json
  public/Data/ProductsData.json
  public/Data/RealCategoryData.json
  public/Data/RealMainProductData.json
  public/Images/Banner/etc/Line Friends 01.png
  public/Images/Banner/etc/LineFriends 02.jpeg
  public/Images/Banner/etc/greenBack.png
  public/Images/Icons/left_arrow.png
  public/Images/Icons/right_arrow.png
  public/Images/Icons/search.png
  public/Images/Logo/black.png
  public/Images/Logo/green.png
  public/Images/Logo/white.png
  public/Images/main_air.jpeg
  public/Images/main_golf.jpeg
  public/Images/main_pink.jpeg
  public/Images/main_room.jpeg
  public/Images/main_yellow.jpeg
  public/index.html
  src/Components/Footer/Footer.js
  src/Components/Footer/Footer.scss
  src/Components/Header/Category/Category.js
  src/Components/Header/Category/Category.scss
  src/Components/Header/Category/CategoryList/CategoryList.js
  src/Components/Header/Category/CategoryList/CategoryList.scss
  src/Components/Header/Header.js
  src/Components/Header/Header.scss
  src/Components/Header/MyInfo/MyInfo.js
  src/Components/Header/MyInfo/MyInfo.scss
  src/Components/Nav/Nav.js
  src/Components/Nav/Nav.scss
  src/Pages/Main/Coupon/Coupon.js
  src/Pages/Main/Coupon/Coupon.scss
  src/Pages/Main/Main.js
  src/Pages/Main/Main.scss
  src/Pages/Main/ProductList/Product/Product.js
  src/Pages/Main/ProductList/Product/Product.scss
  src/Pages/Main/ProductList/ProductList.js
  src/Pages/Main/ProductList/ProductList.scss
  src/Pages/Main/SlickBanner/SlickBanner.js
  src/Pages/Main/SlickBanner/SlickBanner.scss
  src/Pages/MyPage/MyPage.js
  src/Pages/Product/Product.js
  src/Routes.js
  src/Styles/common.scss
  src/index.js
Labels: Status: Accepted

#15 [18기 배담호] 회원가입 유효성검사 기능 및 아이디 중복 확인 수정 완료
  package-lock.json
  package.json
  public/index.html
  src/Pages/Login/Login.js
  src/Pages/Login/Login.scss
  src/Pages/MyPage/MyPage.scss
  src/Pages/Payment/Payment.js
  src/Pages/Payment/Payment.scss
  src/Pages/Product/Product.scss
  src/Pages/Signup/Signup.js
  src/Pages/Signup/Signup.scss
  src/Routes.js
  src/Styles/common.scss
  src/index.js
Labels: Status: 리뷰 요청

#16 [18기 배담호] ADD: 로그인 유효성 검사 구현 / 로그인 유지 체크박스 색상 변경 / 이메일 인증 추가 구현 리뷰 반영
  package-lock.json
  package.json
  src/Pages/Login/Login.js
  src/Pages/Login/Login.scss
  src/Pages/MyPage/MyPage.js
  src/Pages/Product/Product.js
  src/Routes.js
  src/index.js
Labels: Status: 리뷰 요청

#24 [18기 박경현] Routes 컴포넌트 및 경로 정리, 충돌 사항 정리
  package-lock.json
  package.json
  src/Routes.js
  src/index.js
Labels: Status: 리뷰 진행중

#23 [18기 박경현] 카테고리 Link 연결 / localStorage의 user 정보 연결 / 메인 페이지의 상품 관련 추가 구현
  package-lock.json
  public/Data/ProductsData.json
  src/Components/Header/Category/Category.js
  src/Components/Header/Category/CategoryList/CategoryList.js
  src/Components/Header/Category/CategoryList/CategoryList.scss
  src/Components/Header/MyInfo/MyInfo.js
  src/Pages/Main/Main.js
  src/Pages/Main/ProductList/Product/Product.js
  src/Pages/Main/ProductList/Product/Product.scss
  src/Pages/Main/ProductList/ProductList.js
  src/Pages/Payment/Payment.js
  src/Pages/Payment/Payment.scss
  src/Routes.js
Labels: Status: Conflict 해결 요청

#11 [18기 정승옥] URGENT: 찜 기능 / 정렬 기능 수정완료
  package-lock.json
  package.json
  public/Data/ProductData.json
  public/index.html
  src/Components/PageLoad/PageLoad.js
  src/Components/PageLoad/PageLoad.scss
  src/Pages/Login/Login.scss
  src/Pages/Main/Main.js
  src/Pages/Main/Main.scss
  src/Pages/Product/Content/Content.js
  src/Pages/Product/Content/Content.scss
  src/Pages/Product/Content/TopCategory/Component/CategorySelect.js
  src/Pages/Product/Content/TopCategory/Component/CategorySelect.scss
  src/Pages/Product/Content/TopCategory/TopCategory.js
  src/Pages/Product/Content/TopCategory/TopCategory.scss
  src/Pages/Product/Images/spSs_icon_svg.svg
  src/Pages/Product/Product.js
  src/Pages/Product/Product.scss
  src/Pages/Product/ProductList/ListItem/ListItem.js
  src/Pages/Product/ProductList/ListItem/ListItem.scss
  src/Pages/Product/ProductList/ProductList.js
  src/Pages/Product/ProductList/ProductList.scss
  src/Routes.js
  src/Styles/common.scss
  src/config.js
Labels: Status: 리뷰 요청

#28 [18기 박경현] ADD : 메인 페이지에 배너 이미지 추가
  public/Data/MainBannerData.json
  public/Images/Banner/1.png
  public/Images/Banner/2.png
  public/Images/Banner/3.png
  public/Images/Banner/4.png
  public/Images/Banner/5.png
  public/Images/Banner/6.png
  public/Images/Banner/7.png
  src/Pages/Login/Login.scss
  src/Pages/Main/Main.js
  src/Pages/Main/Main.scss
  src/Routes.js
  src/Styles/common.scss
Labels: Status: 리뷰 진행중

#29 [18기 박경현] banner image 경로 local로 변경
  public/Data/MainBannerData.json
Labels: Status: 리뷰 요청

#30 [18기 정승옥] 모달작업
  src/Components/ProductDetailModal/ContentLeft/ContentLeft.js
  src/Components/ProductDetailModal/ContentLeft/ReviewList/Components/DetailList.js
  src/Components/ProductDetailModal/ContentRight/Choice/Chocie.js
  src/Components/ProductDetailModal/ContentRight/Choice/Choice.scss
  src/Components/ProductDetailModal/ContentRight/ContentRight.js
  src/Components/ProductDetailModal/ContentRight/Price/Price.scss
  src/Components/ProductDetailModal/ContentRight/Select/Select.js
  src/Components/ProductDetailModal/ProductDetailModal.js
  src/Pages/Main/Main.js
  src/Pages/Product/Product.js
  src/Pages/Product/Product.scss
  src/Pages/Product/ProductList/ListItem/ListItem.js
  src/Pages/Product/ProductList/ProductList.js
  src/Pages/ProductDetail/ProductDetail.js
  src/Pages/ProductDetail/TopMenu/TopMenu.js
Labels: Status: 리뷰 요청

#31 [18기 배담호] 머지 해주세요 ~
  package-lock.json
  src/Pages/Login/Login.js
  src/Pages/Payment/Payment.js
  src/Pages/Payment/Payment.scss
  src/Pages/Signup/Signup.js
  src/Pages/Signup/Signup.scss
  src/Routes.js
  src/index.js
Labels: Status: 리뷰 요청

#32 [18기 박경현] 텍스트 수정
  src/Pages/Main/SlickBanner/SlickBanner.js
  src/Pages/Main/SlickBanner/SlickBanner.scss
Labels: Status: 리뷰 요청

#27 [18기-라인프렌즈] 최종의 최종의 최종 커밋
  src/Pages/Login/Login.js
  src/Pages/Main/Main.js
  src/Pages/Main/ProductList/Product/Product.js
  src/Pages/MyPage/Modal.js
  src/Pages/MyPage/MyPage.js
  src/Pages/MyPage/MyPageHeart.js
  src/Pages/MyPage/ShoppingBasket/ShoppingProduct.js
  src/Pages/Product/ProductList/ListItem/ListItem.js
  src/Pages/ProductDetail/DetailContainer/Components/ProductImgList.js
  src/Pages/ProductDetail/DetailContainer/DetailContainer.js
  src/Pages/ProductDetail/ProductDetail.js
  src/Pages/ProductDetail/QAContainer/QAAnswer.js
  src/Pages/ProductDetail/QAContainer/QAContainer.js
  src/Pages/ProductDetail/QAContainer/QAModal/QAModal.js
  src/Pages/ProductDetail/ReviewContainer/ReviewContainer.js
  src/Pages/ProductDetail/ReviewContainer/ReviewList/ReviewList.js
  src/Pages/Signup/Signup.js
  src/Routes.js
Labels: Status: 리뷰 요청

#33 [18기 박경현] ADD : 텍스트 수정
  src/Pages/Main/SlickBanner/SlickBanner.js
Labels: Status: 리뷰 요청

#34 [18기 배담호] add : 로그인페이지 회원가입 이동 추가 (머지부탁드립니당)
  src/Pages/Login/Login.js
  src/Pages/Login/Login.scss
  src/Routes.js
Labels: Status: 리뷰 요청

#35 [18기 정승옥] 최종 커밋
  src/Components/Footer/Footer.scss
  src/Components/Header/Category/Category.js
  src/Components/Header/Category/CategoryList/CategoryList.js
  src/Components/Header/Header.js
  src/Components/Header/MyInfo/MyInfo.js
  src/Components/Header/MyInfo/MyInfo.scss
  src/Components/PageLoad/PageLoad.js
  src/Components/PageLoad/PageLoad.scss
  src/Components/ProductDetailModal/ContentLeft/Preview/Preview.js
  src/Components/ProductDetailModal/ContentLeft/ReviewList/Components/DetailList.js
  src/Components/ProductDetailModal/ContentRight/Choice/Chocie.js
  src/Components/ProductDetailModal/ProductDetailModal.scss
  src/Pages/Login/Login.js
  src/Pages/Login/Login.scss
  src/Pages/Main/Main.js
  src/Pages/Main/ProductList/Product/Product.js
  src/Pages/Main/SlickBanner/SlickBanner.js
  src/Pages/MyPage/Modal.js
  src/Pages/MyPage/MyPage.js
  src/Pages/MyPage/MyPage.scss
  src/Pages/MyPage/MyPageAside.js
  src/Pages/MyPage/MyPageHeart.js
  src/Pages/MyPage/MyPageNav.js
  src/Pages/MyPage/MyPageProduct.js
  src/Pages/MyPage/ShoppingBasket/ShoppingBasket.js
  src/Pages/MyPage/ShoppingBasket/ShoppingBasket.scss
  src/Pages/MyPage/ShoppingBasket/ShoppingBasketNavTop.js
  src/Pages/MyPage/ShoppingBasket/ShoppingProduct.js
  src/Pages/MyPage/ShoppingBasket/ShoppingProductList.js
  src/Pages/Payment/Payment.js
  src/Pages/Payment/Payment.scss
  src/Pages/Product/Product.js
  src/Pages/Product/Product.scss
  src/Pages/Product/ProductList/ListItem/ListItem.js
  src/Pages/ProductDetail/DetailContainer/Components/ProductImgList.js
  src/Pages/ProductDetail/Pay/Pay.js
  src/Pages/ProductDetail/Preview/Preview.js
  src/Pages/ProductDetail/ProductDetail.js
  src/Pages/ProductDetail/ProductDetail.scss
  src/Pages/ProductDetail/QAContainer/QAModal/QAModal.js
  src/Pages/ProductDetail/Review/Review.js
  src/Pages/ProductDetail/TopMenu/Components/PayMenu.js
  src/Pages/Signup/Signup.js
  src/Pages/Signup/Signup.scss
  src/Routes.js
Labels: Status: 리뷰 요청
